### ISSUE TITLE
Hosting down in true Path

### ISSUE THREAD

**Issue by marcobaturan** [gsumit1/TruePath#2]
The TruePath extension does not work properly because when I select the web element and select the relative Xpath when the pop-up with the results opens it automatically goes to a Hosting Down warning. Preventing me from accessing the results.

**Comment by gsumit1** [comment]
This issue is already fixed. Last time I added a website link as an iframe so that I can provide more info every now and than. But that site was suspended due to over hits. That was causing the problem. I had already released a new version of TruePath removing the link. Thank you for your support!!!

**Comment by marcobaturan** [comment]
Thank you very much for your time, effort and help.
